CREATE TABLE `stock_base_info` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `code` char(10) NOT NULL DEFAULT '' COMMENT '代码',
  `name` varchar(45) NOT NULL DEFAULT '' COMMENT '名称',
  `pinyin` varchar(100) NOT NULL DEFAULT '' COMMENT '拼音首字母',
  `create_time` bigint(20) NOT NULL DEFAULT '-1' COMMENT '创建日期',
  `update_time` bigint(20) NOT NULL DEFAULT '-1' COMMENT '更新日期',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_code` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='股票基本信息表';


CREATE TABLE `stock_detail_info` (
    `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    `stock_code` CHAR(10) NOT NULL DEFAULT '' COMMENT '股票代码',
    `actual_issue_vol` BIGINT(20) NOT NULL DEFAULT 0 COMMENT '实际发行股数',
    `issue_price` DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT '发行价格',
    `actual_rc_net_amt` DECIMAL(20,2) NOT NULL DEFAULT 0.00 COMMENT '实际募集资金净额',
    `pe_after_issuing` DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT '发行后市盈率',
    `online_success_rate_of_issue` DECIMAL(10,4) NOT NULL DEFAULT 0.0000 COMMENT '网上发行中签率',
    `affiliate_industry` JSON NOT NULL COMMENT '所属行业（JSON格式，包括行业代码和名称）',
    `latest_price` DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT '最新股价',
    `total_shares` BIGINT(20) NOT NULL DEFAULT 0 COMMENT '总股本',
    `circulating_shares` BIGINT(20) NOT NULL DEFAULT 0 COMMENT '流通股',
    `total_market_value` DECIMAL(20,2) NOT NULL DEFAULT 0.00 COMMENT '总市值',
    `circulating_market_value` DECIMAL(20,2) NOT NULL DEFAULT 0.00 COMMENT '流通市值',
    `industry` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '所属行业',
    `listing_date` DATE NOT NULL DEFAULT '1970-01-01' COMMENT '上市时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `idx_stock_code` (`stock_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='股票发行与市值信息表';

CREATE TABLE `company_info` (
    `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    `stock_code` CHAR(10) NOT NULL DEFAULT '' COMMENT '股票代码',
    `org_id` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '企业ID',
    `org_name_cn` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '企业中文全称',
    `org_short_name_cn` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '企业中文简称',
    `org_name_en` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '企业英文全称',
    `org_short_name_en` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '企业英文简称',
    `main_operation_business` TEXT NOT NULL COMMENT '主营业务',
    `operating_scope` TEXT NOT NULL COMMENT '经营范围',
    `district_encode` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '行政区编码',
    `org_cn_introduction` TEXT NOT NULL COMMENT '企业中文介绍',
    `legal_representative` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '法定代表人',
    `general_manager` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '总经理',
    `secretary` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '董事会秘书',
    `established_date` BIGINT(20) NOT NULL DEFAULT 0 COMMENT '成立时间（时间戳毫秒）',
    `reg_asset` DECIMAL(20,2) NOT NULL DEFAULT 0.00 COMMENT '注册资本',
    `staff_num` INT(11) NOT NULL DEFAULT 0 COMMENT '员工人数',
    `telephone` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '联系电话',
    `postcode` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '邮编',
    `fax` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '传真',
    `email` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '邮箱',
    `org_website` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '企业官网',
    `reg_address_cn` VARCHAR(300) NOT NULL DEFAULT '' COMMENT '注册地址（中文）',
    `reg_address_en` VARCHAR(300) NOT NULL DEFAULT '' COMMENT '注册地址（英文）',
    `office_address_cn` VARCHAR(300) NOT NULL DEFAULT '' COMMENT '办公地址（中文）',
    `office_address_en` VARCHAR(300) NOT NULL DEFAULT '' COMMENT '办公地址（英文）',
    `currency_encode` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '货币编码',
    `currency` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '货币',
    `listed_date` BIGINT(20) NOT NULL DEFAULT 0 COMMENT '上市日期（时间戳毫秒）',
    `provincial_name` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '省份名称',
    `actual_controller` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '实际控制人及持股比例',
    `classi_name` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '企业类型',
    `pre_name_cn` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '前身企业名称',
    `chairman` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '董事长',
    `executives_nums` INT(11) NOT NULL DEFAULT 0 COMMENT '高管人数',
    PRIMARY KEY (`id`),
    UNIQUE KEY `idx_stock_code` (`stock_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='企业基础信息表';
